coverage:
  status:
    project: # coverage of project
      default:
        target: 60% # project coverage must be maintained at 60% or higher
    patch: # coverage of lines changed in patch
      default:
        target: 0% # no requirement on patch coverage
